# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Code/capstone_camera_validation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Code/capstone_camera_validation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Code/capstone_camera_validation/CMakeFiles /home/pi/Code/capstone_camera_validation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Code/capstone_camera_validation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server1

# Build rule for target.
server1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 server1
.PHONY : server1

# fast build rule for target.
server1/fast:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/build
.PHONY : server1/fast

Distortion.o: Distortion.cpp.o

.PHONY : Distortion.o

# target to build an object file
Distortion.cpp.o:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/Distortion.cpp.o
.PHONY : Distortion.cpp.o

Distortion.i: Distortion.cpp.i

.PHONY : Distortion.i

# target to preprocess a source file
Distortion.cpp.i:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/Distortion.cpp.i
.PHONY : Distortion.cpp.i

Distortion.s: Distortion.cpp.s

.PHONY : Distortion.s

# target to generate assembly for a file
Distortion.cpp.s:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/Distortion.cpp.s
.PHONY : Distortion.cpp.s

Freeze.o: Freeze.cpp.o

.PHONY : Freeze.o

# target to build an object file
Freeze.cpp.o:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/Freeze.cpp.o
.PHONY : Freeze.cpp.o

Freeze.i: Freeze.cpp.i

.PHONY : Freeze.i

# target to preprocess a source file
Freeze.cpp.i:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/Freeze.cpp.i
.PHONY : Freeze.cpp.i

Freeze.s: Freeze.cpp.s

.PHONY : Freeze.s

# target to generate assembly for a file
Freeze.cpp.s:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/Freeze.cpp.s
.PHONY : Freeze.cpp.s

White.o: White.cpp.o

.PHONY : White.o

# target to build an object file
White.cpp.o:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/White.cpp.o
.PHONY : White.cpp.o

White.i: White.cpp.i

.PHONY : White.i

# target to preprocess a source file
White.cpp.i:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/White.cpp.i
.PHONY : White.cpp.i

White.s: White.cpp.s

.PHONY : White.s

# target to generate assembly for a file
White.cpp.s:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/White.cpp.s
.PHONY : White.cpp.s

corruption.o: corruption.cpp.o

.PHONY : corruption.o

# target to build an object file
corruption.cpp.o:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/corruption.cpp.o
.PHONY : corruption.cpp.o

corruption.i: corruption.cpp.i

.PHONY : corruption.i

# target to preprocess a source file
corruption.cpp.i:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/corruption.cpp.i
.PHONY : corruption.cpp.i

corruption.s: corruption.cpp.s

.PHONY : corruption.s

# target to generate assembly for a file
corruption.cpp.s:
	$(MAKE) -f CMakeFiles/server1.dir/build.make CMakeFiles/server1.dir/corruption.cpp.s
.PHONY : corruption.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... server1"
	@echo "... edit_cache"
	@echo "... Distortion.o"
	@echo "... Distortion.i"
	@echo "... Distortion.s"
	@echo "... Freeze.o"
	@echo "... Freeze.i"
	@echo "... Freeze.s"
	@echo "... White.o"
	@echo "... White.i"
	@echo "... White.s"
	@echo "... corruption.o"
	@echo "... corruption.i"
	@echo "... corruption.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

